//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S22.Imap.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S22.Imap.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attr.zip.
        /// </summary>
        internal static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GifContent {
            get {
                object obj = ResourceManager.GetObject("GifContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * LIST (\HasNoChildren) &quot;/&quot; &quot;INBOX&quot;
        ///* LIST (\Noselect \HasChildren) &quot;/&quot; &quot;[Gmail]&quot;
        ///* LIST (\HasChildren \HasNoChildren \All) &quot;/&quot; &quot;[Gmail]/&amp;A4wDuwOx- &amp;A8QDsQ- &amp;A7wDtwO9A80DvAOxA8QDsQ-&quot;
        ///* LIST (\HasNoChildren \Junk) &quot;/&quot; &quot;[Gmail]/&amp;A5EDvQO1A8ADuQO4A80DvAO3A8QDsQ-&quot;
        ///* LIST (\HasChildren \HasNoChildren \Sent) &quot;/&quot; &quot;[Gmail]/&amp;A5EDwAO1A8MDxAOxA7sDvAOtA70DsQ-&quot;
        ///* LIST (\HasChildren \HasNoChildren \Trash) &quot;/&quot; &quot;[Gmail]/&amp;A5oDrAO0A78Dwg- &amp;A7EDwAO,A8EDwQO5A7wDvAOsA8QDyQO9-&quot;
        ///* LIST (\HasNoChildren \Flagged) &quot;/&quot; &quot;[Gmail]/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImapListResponse {
            get {
                return ResourceManager.GetString("ImapListResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLAXXX_XX.Mu-lti+sub@s_u-b.nifty.com.
        /// </summary>
        internal static string MailFromAddress {
            get {
                return ResourceManager.GetString("MailFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiroyuki Tanaka, Japan.
        /// </summary>
        internal static string MailFromName {
            get {
                return ResourceManager.GetString("MailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;Hiroyuki Tanaka, Japan&quot; &lt;MLAXXX_XX.Mu-lti+sub@s_u-b.nifty.com&gt;
        ///Subject: =?iso-2022-jp?B?GyRCIVpFbEZ8S1xCZz9MOlIhWxsoQg==?=
        ///	=?iso-2022-jp?B?GyRCRWw1fklwQiJMbkI/S2AlLyVpJVYkTjxoQUgkXyFWJF8bKEI=?=
        ///	=?iso-2022-jp?B?GyRCJHMkSiRHJEQkSiQsJG0kJiEhMjszWiROGyhCV0E=?=
        ///	=?iso-2022-jp?B?IRskQiFXJVclbSU4JSclLyVIGyhC?=
        ///Date: Fri, 8 Jul 2011 21:45:55 +0900
        ///MIME-Version: 1.0
        ///Content-Type: multipart/alternative;
        ///	boundary=&quot;----=_NextPart_000_0202_01CC3DB8.948199A0&quot;
        ///Priority: Urgent
        ///X-Priority: 6
        ///X-MSMail-P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailHeader {
            get {
                return ResourceManager.GetString("MailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【東日本大震災】東京武蔵野多摩クラブの取組み「みんなでつながろう　音楽のWA!」プロジェクト.
        /// </summary>
        internal static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iso-2022-jp.
        /// </summary>
        internal static string MailSubjectEncoding {
            get {
                return ResourceManager.GetString("MailSubjectEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: Sun, 10 Nov 2002 23:54:21 +0800
        ///MIME-Version: 1.0
        ///Content-Type: text/plain;
        ///	name=&quot;=?koi8-r?B?1MXT1C50eHQ=?=&quot;
        ///Content-Transfer-Encoding: 7bit
        ///Content-Disposition: attachment;
        ///	filename=&quot;=?koi8-r?B?1MXT1C50eHQ=?=&quot;
        ///
        ///This is an attachment. See issue #28.
        ///.
        /// </summary>
        internal static string MailWithEncodedAttachmentName {
            get {
                return ResourceManager.GetString("MailWithEncodedAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-UIDL-JANA-SERVER: 255392621.1369491686@Jana-Server
        ///From: &quot;Systemadministrator&quot;
        ///Sender: &quot;Systemadministrator&quot;
        ///To: broxi@lcoalmail.loc
        ///Subject: Unzustellbar: test
        ///Date: Sat, 25 May 2013 16:21:24 +0200
        ///Message-ID: 
        ///MIME-Version: 1.0
        ///Content-Type: application/ms-tnef; name=&quot;winmail.dat&quot;
        ///Content-Transfer-Encoding: base64
        ///Content-Disposition: attachment; filename=&quot;winmail.dat&quot;
        ///X-Mailer: Microsoft Outlook 15.0
        ///Thread-Index: AQIWacilbO2h+QbxaliA6L/xOzdkTQ==
        ///
        ///Hello World. See issue #50.
        ///
        ///.
        /// </summary>
        internal static string MailWithInvalidFromHeader {
            get {
                return ResourceManager.GetString("MailWithInvalidFromHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;example_from@dc.edu&gt;
        ///X-SpamCatcher-Score: 1 [X]
        ///Received: from [136.167.40.119] (HELO dc.edu)
        ///	by fe3.dc.edu (CommuniGate Pro SMTP 4.1.8)
        ///	with ESMTP-TLS id 61258719 for example_to@mail.dc.edu; Mon, 23 Aug 2004 11:40:10 -0400
        ///Message-ID: &lt;4129F3CA.2020509@dc.edu&gt;
        ///Date: Mon, 23 Aug 2005 11:40:36 -0400
        ///From: &quot;Taylor (John) Evans&quot; &lt;example_from@dc.edu&gt;
        ///User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.0.1) Gecko/20020823 Netscape/7.0
        ///X-Accept-Language: en-us, en
        ///MIME-Vers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithMIMEComments {
            get {
                return ResourceManager.GetString("MailWithMIMEComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: &quot;xxxxxxx&quot; &lt;xxxxxxx@ms19.hinet.net&gt;
        ///To: &quot;=?big5?B?pUS3UqTAqMm69A==?=&quot; &lt;xxxxxxx@ms19.hinet.net&gt;
        ///Subject: =?big5?B?tbmvuKr4qrqkQKvKq0g=?=
        ///Date: Sun, 10 Nov 2002 23:54:21 +0800
        ///MIME-Version: 1.0
        ///Content-Type: multipart/related;
        ///	boundary=&quot;----=_NextPart_000_000A_01C28914.95B89B50&quot;;
        ///	type=&quot;multipart/alternative&quot;
        ///X-Priority: 3
        ///X-MSMail-Priority: Normal
        ///X-Unsent: 1
        ///X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000
        ///
        ///This is a multi-part message in MIME format.
        ///
        ///------=_NextPart_000_000A_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithMultipleParts {
            get {
                return ResourceManager.GetString("MailWithMultipleParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: from xxx.xxxxx.com (xx.xxxx.com [123.45.67.89])
        ///	by xxxx.asxxx.se (Postfix) with ESMTP id E357F2CCC6A
        ///	for &lt;faktxxx@xxxxxx.se&gt;; Thu,  7 Feb 2013 17:12:05 +0100 (CET)
        ///MIME-Version: 1.0
        ///From: &lt;invxxxxx@xxxxx.com&gt;
        ///To: &lt;faktxxx@xxxxxx.se&gt;
        ///Date: Thu, 7 Feb 2013 17:12:02 +0100
        ///Subject: Fakt__xxxx___xxxx___07_02_2013
        ///Content-Type: multipart/mixed;
        ///	boundary=&quot;--boundary_0_6cb33448-390c-4f02-b75a-2738f1d6dd45&quot;
        ///Message-ID: &lt;44967f46-57cc-47c4-ab9f-1c450e1d87bb@XXXXI0123.xx.xxxx.com&gt;
        ///
        ///----boundar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithoutDisposition {
            get {
                return ResourceManager.GetString("MailWithoutDisposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;xxxxxxx@canon.no&gt;
        ///Received: from mail-gtw.canon.no (mail.canon.no [194.248.71.4])
        ///	by mail29.nsc.no (8.9.3p2/8.9.3) with ESMTP id LAA17991
        ///	for &lt;xxxxxxxx@online.no&gt;; Fri, 4 Jul 2003 11:07:01 +0200 (MEST)
        ///From: &quot;Helpdesk/NL-NOTES,.CANON&quot;@canon.no
        ///Sensitivity: 
        ///Subject: =?ISO-8859-1?Q?Feil_p=E5_PowerShot_A70?=
        ///To: &quot;Martin Bergersen&quot; &lt;xxxxxxxx@online.no&gt;
        ///X-Mailer: Lotus Notes Release 5.0.11   July 24, 2002
        ///Message-ID: &lt;OFA7E5D94E.E33F8ECB-ONC1256D59.0031C285-C1256D59.0031E75A@canon.no&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithQuotedPrintables {
            get {
                return ResourceManager.GetString("MailWithQuotedPrintables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;foo@example.org&gt;
        ///Delivered-To: bar@example.org
        ///Received: (qmail 2543 invoked from network); 4 Sep 1999 09:27:32 -0000
        ///Received: from deathstar.example.org (HELO deathstar.example.org) (192.168.2.2)
        ///  by tie-fighter.example.org with SMTP; 4 Sep 1999 09:27:31 -0000
        ///MIME-Version: 1.0
        ///Subject: RFC 2231
        ///From: foo &lt;foo@example.org&gt;
        ///To: bar &lt;bar@example.org&gt;
        ///X-Mailer: tie-bomber
        ///Date: Sat, 04 Sep 1999 18:26:50 +0900
        ///Message-ID: &lt;19990904092850.5963.foo@example.org&gt;
        ///Content-Type: multipart/mixed; boun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithRfc2231Headers {
            get {
                return ResourceManager.GetString("MailWithRfc2231Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;foo@example.org&gt;
        ///Delivered-To: bar@example.org
        ///Received: (qmail 2543 invoked from network); 4 Sep 1999 09:27:32 -0000
        ///Received: from deathstar.example.org (HELO deathstar.example.org) (192.168.2.2)
        ///  by tie-fighter.example.org with SMTP; 4 Sep 1999 09:27:31 -0000
        ///MIME-Version: 1.0
        ///Subject: RFC 2231
        ///From: foo &lt;foo@example.org&gt;
        ///To: bar &lt;bar@example.org&gt;
        ///X-Mailer: tie-bomber
        ///Date: Sat, 04 Sep 1999 18:26:50 +0900
        ///Message-ID: &lt;19990904092850.5963.foo@example.org&gt;
        ///Content-Type: multipart/mixed; boun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithRfc2231Headers2 {
            get {
                return ResourceManager.GetString("MailWithRfc2231Headers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;From msu.ru!pooh Wed Nov 29 16:17:10 2000 remote from botik
        ///Received: from thicket.nmd.msu.ru([193.232.112.60])
        ///	by pier.botik.ru (Smail-3.2.0.98/botik-0.15 1999-Sep-9 #28) with smtp
        ///	for &lt;xxxxx@botik.ru&gt; id m14176f-002ngXC; Wed, 29 Nov 2000 16:17:05 +0300 (MSK)
        ///Received: (qmail 4233 invoked from network); 29 Nov 2000 13:17:02 -0000
        ///Received: from localhost (HELO msu.ru) (127.0.0.1)
        ///  by localhost with SMTP; 29 Nov 2000 13:17:02 -0000
        ///Message-ID: &lt;3A2501CD.6090804@msu.ru&gt;
        ///Date: Wed, 29 Nov 2000 16: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailWithZipAttachment {
            get {
                return ResourceManager.GetString("MailWithZipAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced By Microsoft MimeOLE V6.0.6002.18463.
        /// </summary>
        internal static string MailXMimeOLE {
            get {
                return ResourceManager.GetString("MailXMimeOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MidiContent {
            get {
                object obj = ResourceManager.GetObject("MidiContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei!
        ///Jeg har nå nylig kjøpt et &quot;PowerShot  A70&quot; digital kamera fra min onkel i
        ///Canon. Det har fungert helt  fint, helt til forige lørdag. Da jeg skrudde
        ///det av, gikk ikke linsen inn  igjen. Og når jeg skrur det på igjen, kommer
        ///&quot;startup&quot; bilde, men så  begynner det å pipe, og viser med beskjeden E18,
        ///og skrur seg  av igjen. Og linsa er fortsatt ute!
        ///Lenger har jeg ikke kommet. Nytter ikke og bytte  batterier, flash card,
        ///eller koble til pc&apos;n. Prøvde å finne et oppslagsverk  etter E18 også, men
        ///forgj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuotedPrintableText {
            get {
                return ResourceManager.GetString("QuotedPrintableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZipAttachment {
            get {
                object obj = ResourceManager.GetObject("ZipAttachment", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
